appointment_system/config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

appointment_system/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

appointment_system/app/models/appointment.rb
class Appointment < ApplicationRecord
end

appointment_system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

appointment_system/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    start_date = params.fetch(:start_date, Date.today).to_date
    @appointments = Appointment.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)    
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointments_url, notice: "La Cita fue creada." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointments_url, notice: "La Cita fue actualizada." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "La Cita fue eliminada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:name, :description, :start_time)
    end
end

appointment_system/app/helpers/application_helper.rb
module ApplicationHelper
end

appointment_system/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

appointment_system/app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p>
    <strong>Name:</strong>
    <%= appointment.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= appointment.description %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= appointment.start_time %>
  </p>

</div>

appointment_system/app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="label">Fecha y hora de la cita:</label>
    <div class="control">
      <%= form.datetime_field :start_time %>
    </div> 
  </div>

  <div class="field mt-5">
    <label class="label">Nombre:</label>
    <div class="control">
      <%= form.text_area :name, class:'textarea' %>
    </div>  
  </div>

  <div class="field">
    <label class="label">Descripción:</label>
    <div class="control">
      <%= form.text_area :description, class:'textarea' %>
    </div>  
  </div>


  <div class="has-text-centered mt-5">
    <%= form.submit "GUARDAR CITA", class:"button is-warning" %>
  </div>
<% end %>

appointment_system/app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Show this appointment", @appointment %> |
  <%= link_to "Back to appointments", appointments_path %>
</div>

appointment_system/app/views/appointments/index.html.erb
<div class="container p-5">

  <div class="columns has-background-white-ter mt3">
    <div class="column">
      <div class="is-size-3 has-text-centered p-3">
        Consultorio del Dr. Verruga Urquieta<br>
        <span class="is-size-5">Sistema Administrador de Citas</span>
      </div>  
    </div>
    <div class="column is-one-fifth">
      <div class="has-text-centered mt-6">
        <%= link_to "AGREGAR CITA", new_appointment_path, class:'button is-warning' %>
      </div>
    </div>
  </div>

  <% if notice %>
    <div class="notice"><%= notice %></div>
  <% end %>

  <%= month_calendar(events: @appointments) do |date, appointments| %>
    <%= date.day %>
    <% appointments.each do |appointment| %>
      
      <div class="py-5 px-3 has-text-centered has-background-white-ter mt-3">
        <%= appointment.start_time.strftime('%H:%M') %> hrs.<br>
        <%= link_to appointment.name, appointment %>
        <div class="mt-3">
          <%= link_to "EDITAR", edit_appointment_path(appointment), class:'button is-small'%>
        </div>
      </div>

    <% end %>

  <% end %>


</div>

appointment_system/app/views/appointments/new.html.erb
<div class="container p-6">
  <div class="columns has-background-white-ter mt3">
    <div class="column">
      <div class="is-size-3 has-text-centered p-3">
        Consultorio del Dr. Verruga Urquieta<br>
        <span class="is-size-5">Sistema Administrador de Citas</span>
      </div>  
    </div>
  </div>
  <div class="is-size-5 mb-5">
    Completa el formulario para agregar una cita:
  </div>
  <%= render "form", appointment: @appointment %>
  <div class="has-text-centered mt-6">
    <%= link_to "Regresar al Calendario", appointments_path %>
  </div>
</div>

appointment_system/app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment %>

<div>
  <%= link_to "Edit this appointment", edit_appointment_path(@appointment) %> |
  <%= link_to "Back to appointments", appointments_path %>

  <%= button_to "Destroy this appointment", @appointment, method: :delete %>
</div>

appointment_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

appointment_system/app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

appointment_system/app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month].capitalize() %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped mt-5">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= l(day, format: '%A') %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

appointment_system/app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>